### ISSUE TITLE
 Error connecting to Bigquery

### ISSUE THREAD

**Issue by Axelmvargas** [Sinaptik-AI/pandas-ai#1115]
### System Info

![image](https://github.com/Sinaptik-AI/pandas-ai/assets/66078703/b46d6c55-cae4-4dc8-8c14-81ca4687a119)

I am trying to replicate the connection model to Bigquery, with a simple test, simply querying a record from a table, but it is not possible since running the script breaks it. What could be the problem?

I am using the PandasAi version 2.0.21

### 🐛 Describe the bug

Unfortunately, I was not able to get your answers, because of the following error:

Query must be a string unless using sqlalchemy.

**Comment by ArslanSaleem** [comment]
@Axelmvargas upgrade to latest pandasAi version it was broken in some previous version now it is fixed

**Comment by Axelmvargas** [comment]
@ArslanSaleem I just updated the version, changed the error, but it still doesn't work.

I was not able to get your answers, because of the following error: SQLCompiler.__init__() got multiple values for argument 'cache_key'

**Comment by Axelmvargas** [comment]
@ArslanSaleem I'm paying attention, the error persists
